spring.config.import=optional:file:./env.properties

spring.application.name=Gestionale_Cassoni

server.port=${PORT:3001}

spring.datasource.url=${JDBC_URI}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}